### ISSUE TITLE
No limit on number of tokens for each turn for the player

### ISSUE THREAD

**Issue by DevashishJoshi** [Jkker/bandit-game-architecture#1]
The [page](https://cs.nyu.edu/courses/fall22/CSCI-GA.2965-001/bandit.html) about this competition says that "Before each pull, P chooses a single slot and bets from one to three tokens"

I'm assuming this means the player can bet either 1 or 2 or 3 tokens in a single turn. However, this is not being observed when running the default client with tokens set to numbers higher than 3.

Note: When the tokens or the slot number is set to 0, the server assumes player wants to stop. When the slot is set to a number higher than s, the server throws an error. Something similar should happen in this case as well.

**Comment by jkker** [comment]
Thanks for reporting this. Fixed in https://github.com/Jkker/bandit-game-architecture/commit/3bb17130e2af1789a4d320e4141c70c0e587cd97
